name: odor_pleasantness
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - mne
  - xgboost
  - jupyter
  - ipykernel
  - pip
  - pip:
      - plotly
      - invoke 